# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # Configuration globale
  config.vm.box_check_update = false
  
  # Machine 1: Web Server (Ubuntu 22.04)
  config.vm.define "web-server" do |web|
    web.vm.box = "ubuntu/jammy64"
    web.vm.hostname = "web-server"
    
    # Configuration réseau
    web.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"
    web.vm.network "private_network", ip: "192.168.56.10"
    
    # Synchronisation des dossiers
    web.vm.synced_folder "./website", "/var/www/html", 
      owner: "www-data", group: "www-data", mount_options: ["dmode=755,fmode=644"]
    
    # Configuration de la machine virtuelle
    web.vm.provider "virtualbox" do |vb|
      vb.name = "web-server-ubuntu"
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    
    # Script de provisioning
    web.vm.provision "shell", path: "scripts/provision-web-ubuntu.sh"
  end

  # Machine 2: Database Server (CentOS 9)
  config.vm.define "db-server" do |db|
    db.vm.box = "generic/centos9s"
    db.vm.hostname = "db-server"
    
    # Configuration réseau
    db.vm.network "private_network", ip: "192.168.56.20"
    
    # Port forwarding pour MySQL
    db.vm.network "forwarded_port", guest: 3306, host: 3307
    
    # Synchronisation pour les scripts SQL
    db.vm.synced_folder "./database", "/tmp/database"
    
    # Configuration de la machine virtuelle
    db.vm.provider "virtualbox" do |vb|
      vb.name = "db-server-centos"
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    
    # Script de provisioning
    db.vm.provision "shell", path: "scripts/provision-db-centos.sh"
  end
end